### PR TITLE
Issue140 retention policy in async mode

### PR DESCRIPTION
**Pull request by rockclimber73**

### CODE REVIEW

**Comment by dmke** [comment]
This looks good.

Do you mind if I squash some of your commits?

**Comment by rockclimber73** [comment]
Of course I don't mind :)

**Comment by rockclimber73** [comment]
I thought that squashing someone else's commits might be pretty boring, so I decided to do it myself. If you want to change something else just tell me or, of course, you can do it yourself

**Comment by rockclimber73** [comment]
It looks like `robocop` has been updated to 0.51. There are new offenses detected throughout the project

**Comment by dmke** [comment]
Oh, I totally forgot about this... This week was a little crazy, work-wise.

Thank you for squashing, I will merge this in a moment.

Don't worry about robocop, I will either fix the offenses after merging or pinning it to 0.50.x :-)

**Comment by dmke** [comment]
Version 0.5.0 is now released. Thank you again for your work!

**Comment by dmke** [comment]
0.4.3 now issues a warning if you already (accidentally) provide precision, RP and/or DB arguments. That should minimize potential data inconsistencies.

**Pull request merged**
