### PR TITLE
docs: added link to v2 client

### PR DESCRIPTION
**Pull request by bednar**
Added a link to v2 client that clarify clients compatibility.

### CODE REVIEW

**Review by Esity — DISMISSED** [review]
See conversation comment

**Review by hennevogel — APPROVED** [review]
For now there are two right? No need to conceal that IMHO...

**Comment by hennevogel** [comment]
@Esity can you dismiss you review and we discuss this in the [ruby-maintainer](https://github.com/orgs/influxdata/teams/ruby-maintainers/discussions/2) group?

**Comment by Esity** [comment]
@hennevogel dismissed

**Pull request merged**
